# Generated by Django 5.0.6 on 2024-07-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmanager_project_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='dept',
            field=models.CharField(default='CSE', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='rank',
            field=models.CharField(default='Lecturer', max_length=200),
        ),
    ]
