# Generated by Django 5.0.6 on 2024-07-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectmanager_dept_projectmanager_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectmanager',
        ),
    ]
