# Generated by Django 5.0.6 on 2024-07-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectmanager'),
        ),
    ]
