# Generated by Django 5.0.6 on 2024-07-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_projectmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanager',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='rank',
        ),
    ]
