# Generated by Django 5.0.6 on 2024-07-03 22:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_projectmanager_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectmanagername',
            field=models.CharField(default='NEW', max_length=200, verbose_name=api.models.ProjectManager),
        ),
    ]
