# Generated by Django 5.0.6 on 2024-07-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_projectmanagername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='name',
            new_name='nam',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectmanagername',
        ),
    ]
