# Generated by Django 5.0.6 on 2024-07-03 22:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_name_projectmanager_nam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='nam',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='projectmanagername',
            field=models.CharField(default='NULL', max_length=200, verbose_name=api.models.ProjectManager),
        ),
    ]
