# Generated by Django 5.0.6 on 2024-07-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_nam_projectmanager_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectmanagername',
        ),
    ]
