# Generated by Django 5.0.6 on 2024-07-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_project_projectmanagername'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_email',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='student_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='student_roll',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
