# Generated by Django 5.0.6 on 2024-07-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_student_email_project_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='student_email',
            new_name='student_contact',
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='dept',
            field=models.CharField(default='CSE', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='manager_contact',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='rank',
            field=models.CharField(default='Lecturer', max_length=200),
        ),
    ]
