# Generated by Django 5.0.6 on 2024-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_student_email_project_student_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student_roll',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
